### ISSUE TITLE
In p2pmem-test, pread() stuck

### ISSUE THREAD

**Issue by joshualin-petaio** [Eideticom/p2pmem-pci#10]
Hi,

I have two NVMe device with CMB.
When I want to use pread() form /dev/nvme0n1 to /dev/p2pmem0, it will stuck.
I trace the code and found it is fail in kernel function pci_p2pdma_map_sg_attrs().
It always report p2pdma map type unknown (PCI_P2PDMA_MAP_UNKNOWN).
Could you help me or give me some comment to fix this issue ?

Thank,
Joshua Lin

OS: Ubuntu 18.04.4 LTS
Kernel: 5.14.10
(re-build kernel and enable CONFIG_PCI_P2PDMA)

**Comment by lsgunth** [comment]
Upstream kernels do not support what you are trying to do. This repo is ancient, a giant hack and shouldn't be used for anything. 
Better to use the work here: https://lore.kernel.org/all/20210916234100.122368-1-logang@deltatee.com/T/#u

**Comment by joshualin-petaio** [comment]
Hi lsgunth, 
Thank you for your reply. 
I will try https://github.com/sbates130272/linux-p2pmem/ first. 
This issue can be close now. 
Thank you. 
Joshua
