### ISSUE TITLE
Do we still support EP with BAR exposed to user space as bounce buffer?

### ISSUE THREAD

**Issue by jumpmanhou** [Eideticom/p2pmem-pci#12]
Hi,
I have no NVMe with CMB, but I have an FPGA that can be configured with a BAR mapped to its internal LPDDR.  I tried this repo and exposed the BAR to user space as /dev/p2pmem0. But when I ran the p2pmem-test application, like "./p2pmem-test /dev/nvme0n1 /dev/nvme1n1 /dev/p2pmem0 -c 1 -s 4k --check" .
It ends up with a pwrite I/O error. 
From the dmesg I can see the "blk_update_request: I/O error, dev nvme0n1, sector 0 op 0x1:(WRITE) flags 0x8800 phys_seg 1 prio class 0" error message. 
So I am curious if we still have the bounce buffer support in p2pmem. Thanks in advance!

**Comment by lsgunth** [comment]
This repo as ancient and unsupported. 

There are recent patches in Linux v6.2 that could help support you in doing this though. The BAR cannot be exposed in a basic way, and must be done using the pci-p2pdma infrastructure. 

See this for the patchset that enables userspace p2pdma for NVMe CMBs:

https://lore.kernel.org/all/20220922163926.7077-1-logang@deltatee.com/T/#r228acc8dabe86a2e8108728d8bcfece7a8a2e00c

Drivers that enable p2p memory can allocate it through the sysfs interface in /sys/<pcidev>/p2pmem/alloc.

You can also look at the p2pdma code here:

https://elixir.bootlin.com/linux/v6.2.1/source/drivers/pci/p2pdma.c

**Comment by jumpmanhou** [comment]
Thanks, Logan. I will take a look at those patches first.
