### ISSUE TITLE
Calling open() to /dev/p2pmemX fails, returning EINVAL

### ISSUE THREAD

**Issue by insujang** [Eideticom/p2pmem-pci#8]
OS: Ubuntu 18.04.4 LTS
Kernel: 4.20.0

I am currently testing a custom device driver with p2pmem-pci userspace driver. My goal is to write a data to device's MMIO register through p2pmem-pci device.

```
#define _GNU_SOURCE 1
...
int fd = open("/dev/p2pmem0", O_WRONLY | O_DIRECT);
```

The `open()` returns -EINVAL due to O_DIRECT flag. If I remove O_DIRECT, `open()` succeeds but write operations do not work as intended (no MMIO write).
Manual of `open()` says the filesystem should not have journaling, which requires write buffer, so I also run the program in the journal-disabled ext4 fs, but have no lock.

Could you please let me know what should I do to make O_DIRECT works?

**Comment by sbates130272** [comment]
Hi @insujang 

You should not open the /dev/p2pmem0 with O_DIRECT. And you certainly should not write to the file descriptor obtained via the open on the p2pdma device using load/stores on the CPU unless you are looking for poor performance.

I recommend you review the README.md in the [p2pmem-test][1] repo and review the source code in that for an example of how to implement p2pdma in userspace.

"My goal is to write a data to device's MMIO register through p2pmem-pci device." Can you elaborate on this more? Are you trying to write to the MMIO on the p2pmem-pci device from an adjacent PCIe device in the server?

[1]: https://github.com/sbates130272/p2pmem-test

**Comment by insujang** [comment]
@sbates130272 , Thank you for the detailed reply!

Maybe I misunderstand the usage of p2pdma-pci.. Right now I have no idea but I should explore the code and README you provided. :)

> "My goal is to write a data to device's MMIO register through p2pmem-pci device." Can you elaborate on this more? Are you trying to write to the MMIO on the p2pmem-pci device from an adjacent PCIe device in the server?

Yes. I am trying to write to the MMIO on the p2pmem-pci device from an adjacent PCIe device (in my case, this PCIe device is an Infiniband RDMA HCA), and expecting that this write is eventually written to the associated MMIO on another PCIe device (that exposed its MMIO with p2pmem) (data flow: RDMA HCA -> p2pmem-pci -> another PCIe device).

To be more specific, what I am trying to do is a RDMA MMIO write (similar to RDMA write, but target address is not physical memory, but PCIe MMIO BAR).
`ibv_reg_mr()`, which uses `get_user_pages()` kernel function in Infiniband kernel modules, does not support memory region registration for MMIO (non-physical memory region). Therefore, I am trying to use p2pmem-pci module as a solution for this.

1. My custom device driver for target device is modified to use `pci_p2pmem_add_resource()` so that `p2pmem-pci` kernel module recognizes it and creates the corresponding `/dev/p2pmemX` device.
2. When `/dev/p2pmem0` device is created, what I tried to do is to open this device and get virtual addresses from it through `open()` and `mmap()` from my userspace process. (that you said I should not)
3. The userspace process is an RDMA peer (let's call it as peer A), so it registers the mapped address to RDMA HCA through `ibv_reg_mr()`.
4. When a peer node sends a value to peer A, I expect this value is written to my peer A's device's PCIe MMIO BAR register through p2pmem-pci device, using it as a buffer for the target device.

Did I misunderstand something about p2pmem-pci regarding step 3 and 4? I thought that it is a similar case to the p2pmem-test example...

**Comment by insujang** [comment]
If I understand p2pmem-test code correctly, it uses p2pmem device as follows.

> Some simple examples: ./p2pmem-test /dev/nvme0n1 /dev/nvme1n1 /dev/p2pmem0 -c 1 -s 4k --check

- `/dev/p2pmem0` is used as a buffer of data copy from `/dev/nvme0n1` to `/dev/nvme1n1`.
- Two devices `/dev/nvme0n1` and `/dev/nvme1n1` is opened with `CFG_FD_RDWR_DIRECT_NC` flag (converted to: `O_TRUNC | O_WRONLY | O_DIRECT` by libargconfig).
- p2pmem device `/dev/p2pmem0` is opened with `CFG_FD_RDWR_NC` (converted to: `O_TRUNC | O_RDWR` by libargconfig). Opened p2pmem fd is stored in `cfg.p2pmem_fd`.
- When `cfg.p2pmem_fd` is set, test code calls `mmap()` to get virtual address mapped on `/dev/p2pmem0` [[src]](https://github.com/sbates130272/p2pmem-test/blob/master/src/main.c#L523), and stores the address to `cfg.buffer`.
- Thread function `thread_run` reads a data from `/dev/nvme0n1` to `cfg.buffer`, which points `/dev/p2pmem0`'s buffer [[src]](https://github.com/sbates130272/p2pmem-test/blob/master/src/main.c#L290), and then writes a data from `/dev/p2pmem0`'s buffer to `/dev/nvme1n1` [[src]](https://github.com/sbates130272/p2pmem-test/blob/master/src/main.c#L308).

What I am confused is how p2p dma works with p2pmem-pci. Function calls `pread()` and `pwrite()` are explicitly divided. If the buffer is a normal memory, it would be double copy (`nvme0n1` -> memory buffer, and memory buffer -> `nvme1n1`). But in this case the buffer is a `p2pmem-pci` device's MMIO, so data is actually copied *directly from `nvme0n1` to `nvme1n1`* at the moment the `pwrite()` is called..?

Here is a gap between what the code actually seems do and my understanding summarized again:
- My thought: copy data to p2pmem-pci device buffer. Then data is copied automatically to the associated PCIe device's MMIO.
- Code: copy data to p2pmem-pci device buffer, and then copy data from p2pmem-pci device buffer to target device's MMIO (both function calls are required). It seems double copy, but p2pmem-pci buffer is a special type of memory so data is directly copied from the source device to the target device. Why two distinct operations (`read`, and `write`) are necessary? Would direct `memcpy` from mapped buffer of nvme0n1 to that of nvme1n1 not work?

Sorry for asking basic p2p questions..! I could only find high-level explanations so I cannot understand details yet.

**Comment by sbates130272** [comment]
@insujang let's start by dropping the term MMIO from this conversation. MMIO normally implies the memory region has some effect on the device it is located on (e.g. a doorbell or a register write and read). From your discussion above you just want to write and read to a PCIe BAR with no side-effects.

You said

"When /dev/p2pmem0 device is created, what I tried to do is to open this device and get virtual addresses from it through open() and mmap() from my userspace process. (that you said I should not)"

NO! I did not say you should **not** do this. I said you should not use O_DIRECT on the open(). You definintely want to open() and mmap() the /dev/p2pmem0 to get a virtual address that maps to your PCIe BAR.

Forget about RDMA for now. First see if you can get p2pmem-test working and that you can understand its code.

"What I am confused is how p2p dma works with p2pmem-pci. Function calls pread() and pwrite() are explicitly divided. If the buffer is a normal memory, it would be double copy (nvme0n1 -> memory buffer, and memory buffer -> nvme1n1). But in this case the buffer is a p2pmem-pci device's MMIO, so data is actually copied directly from nvme0n1 to nvme1n1 at the moment the pwrite() is called..?"

p2pmem is identical to system mem in terms of how data moves from nvme0n1 to nvme 1n1. Two operations (a read followed by a write) are needed and those reads and writes are issued to the NVMe devices using a memory pointer that points to the memory on the p2pmem device. You should not be calling pwrite or pread on the p2pmem device itself. Pass it in to calls aimed at the NVMe devices.

**Comment by insujang** [comment]
@sbates130272 Thank you for clarifying it! As you suggested I should look more at the code and test it.
I clearly understand that I should not use O_DIRECT on calling `open()`to `/dev/p2pmemX`, so I think this issue should be closed and open another conversation thread with more proper topic and more detailed explanation of my situation. May I?

Thanks again for your help!
